### ISSUE TITLE
NPE While using Restrict Play 2.4

### ISSUE THREAD

**Issue by rakesh-roshan** [schaloner/deadbolt-2#67]
My DeadBoltHandler is 

public class GPSDeadboltHandler extends AbstractDeadboltHandler {

	@Override
	public F.Promise<Optional<Result>> beforeAuthCheck(Context context) {
		// TODO Auto-generated method stub
		return F.Promise.pure(null);
	}

	@Override
	public F.Promise<Optional<Subject>> getSubject(Context context) {
		// TODO Auto-generated method stub
		Injector injector = Play.application().injector();
		injector.instanceOf(PersistenceInitializer.class);
		final SecureUserService accountService = injector.instanceOf(SecureUserService.class);
		
		return F.Promise.promise(() -> Optional.ofNullable(accountService.find(1L)));
	}

	@Override
	public F.Promise<Result> onAuthFailure(Context context, String content) {
		// TODO Auto-generated method stub
		return F.Promise.promise(() -> forbidden("accessDenied"));
	}

	@Override
	public F.Promise<Optional<DynamicResourceHandler>> getDynamicResourceHandler(
			Context context) {
		// TODO Auto-generated method stub
		return F.Promise.pure(null);
	}

}

SubjectPresent works fine.

But Restrict is giving NPE.

The use is 
@Restrict(@Group("Admin"))
	public Result gpsData() {
		Injector injector = Play.application().injector();
		injector.instanceOf(PersistenceInitializer.class);
		final GpsDataService gpsDataService = injector.instanceOf(GpsDataService.class);
		GpsData gpsData = gpsDataService.find(424L);
		Logger.debug("Found gps Data entry: " + gpsData);
		return ok(gpsData.toString()).as("text/json");
		
	}

THe exception:

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.3.jar:2.4.3]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.3.jar:2.4.3]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.3.jar:2.4.3]
        at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.3.jar:2.4.3]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.3.jar:2.4.3]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.3.jar:2.4.3]
        at scala.Option.getOrElse(Option.scala:121) [scala-library-2.11.6.jar:na]
        at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.3.jar:2.4.3]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.3.jar:2.4.3]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.3.jar:2.4.3]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.3.jar:2.4.3]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.6.jar:na]
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [scala-library-2.11.6.jar:na]
        at scala.util.Try$.apply(Try.scala:191) [scala-library-2.11.6.jar:na]
        at scala.util.Failure.recover(Try.scala:215) [scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.3.jar:2.4.3]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.3.jar:2.4.3]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.6.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.6.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
Caused by: java.lang.NullPointerException: null
        at be.objectify.deadbolt.java.actions.AbstractRestrictiveAction.lambda$execute$13(AbstractRestrictiveAction.java:64) ~[deadbolt-java_2.11-2.4.3.jar:2.4.3]
        at be.objectify.deadbolt.java.actions.AbstractRestrictiveAction$$Lambda$45/475955609.apply(Unknown Source) ~[na:na]
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106) ~[play_2.11-2.4.3.jar:2.4.3]
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106) ~[play_2.11-2.4.3.jar:2.4.3]
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[play_2.11-2.4.3.jar:2.4.3]
        ... 6 common frames omitted

**Comment by rakesh-roshan** [comment]
After looking at your examples I figured out that instead of null I should return Optional::Empty from preAuth method. That fixed it.

**Comment by schaloner** [comment]
You beat me to it - indeed, that's the solution.

    public F.Promise<Optional<Result>> beforeAuthCheck(Context context) {
        // TODO Auto-generated method stub
        return F.Promise.pure(Optional.empty());
    }
