### ISSUE TITLE
@Transactional annotation breaks when using @DeferredDeadbolt

### ISSUE THREAD

**Issue by sindrit** [schaloner/deadbolt-2#68]
I'm using play 2.4.3 and deadbolt-java 2.4.3.

It a play controller is annotated with @DeferredDeadbolt and has some action methods with @Transactional the DeferredDeadboltAction breaks the Ebean transaction mechanism.

@Transactional adds the play.db.ebean.TransactionalAction which simply wraps the deligate in Ebean.execute() which rolls back the transaction if it catches an exception.

```
    return Ebean.execute(new TxCallable<F.Promise<Result>>() {
        public F.Promise<Result> call() {
            try {
                return delegate.call(ctx);
            } catch (RuntimeException e) {
                throw e;
            } catch (Throwable t) {
                throw new RuntimeException(t);
            }
        }
    });
```

DeferredDeadboltAction however wraps the call to the delegate in a Promise, meaning the exception propogates up a different call stack.

DeferredDeadboltAction get the following call stack

```
  at be.objectify.deadbolt.java.actions.DeferredDeadboltAction.execute(DeferredDeadboltAction.java:62)
  at be.objectify.deadbolt.java.actions.AbstractDeadboltAction.call(AbstractDeadboltAction.java:125)
  at controllers.extranet.annotations.CatcherAction.call(CatcherAction.java:13)
  at controllers.extranet.annotations.TemplateVarsAction.call(TemplateVarsAction.java:43)
  at play.mvc.Security$AuthenticatedAction.call(Security.java:53)
  at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:22)
  at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:19)
  at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:673)
  at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:667)
  at com.avaje.ebean.Ebean.execute(Ebean.java:1393)
  at play.db.ebean.TransactionalAction.call(TransactionalAction.java:19)
  at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
  at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
  at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
  at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
  at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
  at scala.concurrent.impl.Future$.apply(Future.scala:31)
  at scala.concurrent.Future$.apply(Future.scala:492)
  at play.core.j.JavaAction.apply(JavaAction.scala:94)
  at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
  at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
```

But the action with the business logic gets a call stack without the TransactionalAction.call

```
  at controllers.extranet.Bookings.changeRoomRate(Bookings.java:1652)
  at extranet.Routes$$anonfun$routes$1$$anonfun$applyOrElse$130$$anonfun$apply$130.apply(Routes.scala:15443)
  at extranet.Routes$$anonfun$routes$1$$anonfun$applyOrElse$130$$anonfun$apply$130.apply(Routes.scala:15443)
  at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
  at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
  at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
  at play.GlobalSettings$1.call(GlobalSettings.java:67)
  at be.objectify.deadbolt.java.actions.DeferredDeadboltAction.lambda$execute$20(DeferredDeadboltAction.java:69)
  at be.objectify.deadbolt.java.actions.DeferredDeadboltAction$$Lambda$57.1219228195.apply(Unknown Source:-1)
  at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106)
  at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106)
  at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
  at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
  at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:399)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I have found a workaround for this where setting deadbolt.java.blocking=true causes DeferredDeadboltAction to call the deligate in the same call stack, allowing exceptions to propogate to the TransactionalAction. This however leads to problems with the blocking timeout.

**Comment by schaloner** [comment]
Unfortunately, this is a case where you can only have one of the two solutions proposed above.  There's a discussion of the same problem with regards to JPA [here](https://github.com/schaloner/deadbolt-2-java/issues/7).

**Comment by sindrit** [comment]
I ended up migrating away from using DeferredDeadbolt, as far as I can tell my app was using DeferredDeadbolt because my DeadboltHandler was unable to find the correct Subject if some other Actions had not run already. My DeadboltHandler now implements beforeAuthCheck() to find the Subject and @Restrict without deferred works fine now (with @Transactional).

**Comment by mkurz** [comment]
@sindrit You could also try to set
```
deadbolt.java.blocking=true
```
in `application.conf`

**Comment by dhirenpratap** [comment]
In play 2.5.2 It's breaking for me as well.

Any resolutions?

**Comment by dhirenpratap** [comment]
Another work-around is, switch the order of annotation. It works as expected.

```
@SubjectPresent
@Transactional
    public Result addInvoice() {
           dboperations1();
           dboperations2();
          dboperations3();
          return  ok("success"):
    }
```

**Comment by mkurz** [comment]
This can be closed.

Thanks to these commits and pull requests
https://github.com/schaloner/deadbolt-2-java/commit/0fd0ef1afd9ebcc3fca030b6e34b8a1745dbb8f4
https://github.com/schaloner/deadbolt-2-java/commit/e54707efc6ac2904a6f69f96b0c0b01f46f5d2a6
https://github.com/schaloner/deadbolt-2-java/pull/52
deadbolt now doesn't switch the thread anymore which led to the problems described above.

Also there is the `deadbolt.java.blocking=true` setting which help people to run code synchronous.

Plus since Play 2.5 people can use `play.http.actionComposition.controllerAnnotationsFirst = [true | false]` to controll if controller annotations should run before or after the method ones.

Since all people in this thread could solve their problems plus the config options I described I can't see why we should keep this issue here open any longer.

**Comment by eximius313** [comment]
@mkurz shouldn't it also be documented here: https://github.com/schaloner/deadbolt-2-java/issues/89 ?

**Comment by mkurz** [comment]
@eximius313 I added `play.http.actionComposition.controllerAnnotationsFirst` to the tracking ticket. The blocking config is already in the docs I think.
